// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingOrder.API.Delivery.INfrastructure.Configuration;

#nullable disable

namespace TrackingOrder.API.Delivery.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrackingOrder.API.Delivery.INfrastructure.Entities.OrderTracking", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeliveryPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryVehicle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.ToTable("OrderTrackings");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("f7948d66-ae41-4a2b-8a41-a5dea5750243"),
                            DeliveryPerson = "John Doe",
                            DeliveryVehicle = "Truck",
                            IsDelivered = false,
                            Location = "Warehouse",
                            PhoneNumber = "123456789",
                            Status = "In Progress",
                            UpdateDate = new DateTime(2024, 1, 23, 22, 1, 35, 146, DateTimeKind.Local).AddTicks(3376)
                        },
                        new
                        {
                            OrderId = new Guid("ab3c1a63-fefa-4934-824b-e4b5201cb84a"),
                            DeliveryPerson = "Jane Smith",
                            DeliveryVehicle = "Van",
                            IsDelivered = true,
                            Location = "Customer's Address",
                            PhoneNumber = "987654321",
                            Status = "Delivered",
                            UpdateDate = new DateTime(2024, 1, 23, 22, 1, 35, 146, DateTimeKind.Local).AddTicks(3390)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
